name=USMP_Demo
version=0.1.0
author=Akhil B Xavier <itswinterx64@gmail.com>
maintainer=Akhil B Xavier <itswinterx64@gmail.com>
sentence=Demo Arduino library for USMP (Unified Secure Multi-transport Protocol).
paragraph=A lightweight secure communication protocol for microcontrollers.
category=Communication
url=https://usmp.metaloom.in
architectures=*
includes=USMP_Demo.h
